query CommitDetail($ownerSlug: String!, $repoSlug: String!, $oid: String!) {
  repositories(
    filter: {
      slug: { equalTo: $repoSlug }
      or: [
        { owner: { username: { equalTo: $ownerSlug } } }
        { organization: { slug: { equalTo: $ownerSlug } } }
        { organization: { idpOrganizationId: { equalTo: $ownerSlug } } }
      ]    }
    first: 1
  ) {
    nodes {
      rowId
      commit(sha: $oid) {
        oid
        message
        messageHeadline
        committedDate
        authoredDate
        author {
          name
          email
        }
        parents {
          oid
        }
        changedFiles {
          path
          oldPath
          status
          oldOid
          newOid
          isBinary
          isImage
          additions
          deletions
        }
      }
    }
  }
}
