query PullRequestFileDiff(
  $ownerSlug: String!
  $repoSlug: String!
  $number: Int!
  $path: String!
) {
  pullRequests(
    filter: {
      number: { equalTo: $number }
      repository: {
        slug: { equalTo: $repoSlug }
        or: [
          { owner: { username: { equalTo: $ownerSlug } } }
          { organization: { slug: { equalTo: $ownerSlug } } }
          { organization: { idpOrganizationId: { equalTo: $ownerSlug } } }
        ]      }
    }
    first: 1
  ) {
    nodes {
      id
      rowId
      fileDiff(path: $path) {
        path
        status
        isBinary
        oldText
        newText
      }
    }
  }
}
