/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RepositoriesRouteImport } from './routes/repositories'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepositoriesOwnerRepoRouteImport } from './routes/repositories/$owner/$repo'

const RepositoriesRoute = RepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesOwnerRepoRoute = RepositoriesOwnerRepoRouteImport.update({
  id: '/$owner/$repo',
  path: '/$owner/$repo',
  getParentRoute: () => RepositoriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/repositories': typeof RepositoriesRouteWithChildren
  '/repositories/$owner/$repo': typeof RepositoriesOwnerRepoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/repositories': typeof RepositoriesRouteWithChildren
  '/repositories/$owner/$repo': typeof RepositoriesOwnerRepoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/repositories': typeof RepositoriesRouteWithChildren
  '/repositories/$owner/$repo': typeof RepositoriesOwnerRepoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects' | '/repositories' | '/repositories/$owner/$repo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects' | '/repositories' | '/repositories/$owner/$repo'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/repositories'
    | '/repositories/$owner/$repo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRoute
  RepositoriesRoute: typeof RepositoriesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$owner/$repo': {
      id: '/repositories/$owner/$repo'
      path: '/$owner/$repo'
      fullPath: '/repositories/$owner/$repo'
      preLoaderRoute: typeof RepositoriesOwnerRepoRouteImport
      parentRoute: typeof RepositoriesRoute
    }
  }
}

interface RepositoriesRouteChildren {
  RepositoriesOwnerRepoRoute: typeof RepositoriesOwnerRepoRoute
}

const RepositoriesRouteChildren: RepositoriesRouteChildren = {
  RepositoriesOwnerRepoRoute: RepositoriesOwnerRepoRoute,
}

const RepositoriesRouteWithChildren = RepositoriesRoute._addFileChildren(
  RepositoriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRoute,
  RepositoriesRoute: RepositoriesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
