/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthGraphRouteImport } from './routes/_auth/graph'
import { Route as AuthRepositoriesIndexRouteImport } from './routes/_auth/repositories/index'
import { Route as AuthOrganizationsIndexRouteImport } from './routes/_auth/organizations/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthOrganizationsOrgSlugIndexRouteImport } from './routes/_auth/organizations/$orgSlug/index'
import { Route as AuthRepositoriesOwnerRepoRouteImport } from './routes/_auth/repositories/$owner.$repo'
import { Route as AuthRepositoriesOwnerRepoCommitsRouteImport } from './routes/_auth/repositories/$owner.$repo/commits'
import { Route as AuthRepositoriesOwnerRepoBranchesRouteImport } from './routes/_auth/repositories/$owner.$repo/branches'
import { Route as AuthRepositoriesOwnerRepoPullsIndexRouteImport } from './routes/_auth/repositories/$owner.$repo/pulls/index'
import { Route as AuthRepositoriesOwnerRepoPullsNewRouteImport } from './routes/_auth/repositories/$owner.$repo/pulls/new'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGraphRoute = AuthGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRepositoriesIndexRoute = AuthRepositoriesIndexRouteImport.update({
  id: '/repositories/',
  path: '/repositories/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrganizationsIndexRoute = AuthOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOrganizationsOrgSlugIndexRoute =
  AuthOrganizationsOrgSlugIndexRouteImport.update({
    id: '/organizations/$orgSlug/',
    path: '/organizations/$orgSlug/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthRepositoriesOwnerRepoRoute =
  AuthRepositoriesOwnerRepoRouteImport.update({
    id: '/repositories/$owner/$repo',
    path: '/repositories/$owner/$repo',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthRepositoriesOwnerRepoCommitsRoute =
  AuthRepositoriesOwnerRepoCommitsRouteImport.update({
    id: '/commits',
    path: '/commits',
    getParentRoute: () => AuthRepositoriesOwnerRepoRoute,
  } as any)
const AuthRepositoriesOwnerRepoBranchesRoute =
  AuthRepositoriesOwnerRepoBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthRepositoriesOwnerRepoRoute,
  } as any)
const AuthRepositoriesOwnerRepoPullsIndexRoute =
  AuthRepositoriesOwnerRepoPullsIndexRouteImport.update({
    id: '/pulls/',
    path: '/pulls/',
    getParentRoute: () => AuthRepositoriesOwnerRepoRoute,
  } as any)
const AuthRepositoriesOwnerRepoPullsNewRoute =
  AuthRepositoriesOwnerRepoPullsNewRouteImport.update({
    id: '/pulls/new',
    path: '/pulls/new',
    getParentRoute: () => AuthRepositoriesOwnerRepoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graph': typeof AuthGraphRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organizations': typeof AuthOrganizationsIndexRoute
  '/repositories': typeof AuthRepositoriesIndexRoute
  '/repositories/$owner/$repo': typeof AuthRepositoriesOwnerRepoRouteWithChildren
  '/organizations/$orgSlug': typeof AuthOrganizationsOrgSlugIndexRoute
  '/repositories/$owner/$repo/branches': typeof AuthRepositoriesOwnerRepoBranchesRoute
  '/repositories/$owner/$repo/commits': typeof AuthRepositoriesOwnerRepoCommitsRoute
  '/repositories/$owner/$repo/pulls/new': typeof AuthRepositoriesOwnerRepoPullsNewRoute
  '/repositories/$owner/$repo/pulls': typeof AuthRepositoriesOwnerRepoPullsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graph': typeof AuthGraphRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organizations': typeof AuthOrganizationsIndexRoute
  '/repositories': typeof AuthRepositoriesIndexRoute
  '/repositories/$owner/$repo': typeof AuthRepositoriesOwnerRepoRouteWithChildren
  '/organizations/$orgSlug': typeof AuthOrganizationsOrgSlugIndexRoute
  '/repositories/$owner/$repo/branches': typeof AuthRepositoriesOwnerRepoBranchesRoute
  '/repositories/$owner/$repo/commits': typeof AuthRepositoriesOwnerRepoCommitsRoute
  '/repositories/$owner/$repo/pulls/new': typeof AuthRepositoriesOwnerRepoPullsNewRoute
  '/repositories/$owner/$repo/pulls': typeof AuthRepositoriesOwnerRepoPullsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/graph': typeof AuthGraphRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/organizations/': typeof AuthOrganizationsIndexRoute
  '/_auth/repositories/': typeof AuthRepositoriesIndexRoute
  '/_auth/repositories/$owner/$repo': typeof AuthRepositoriesOwnerRepoRouteWithChildren
  '/_auth/organizations/$orgSlug/': typeof AuthOrganizationsOrgSlugIndexRoute
  '/_auth/repositories/$owner/$repo/branches': typeof AuthRepositoriesOwnerRepoBranchesRoute
  '/_auth/repositories/$owner/$repo/commits': typeof AuthRepositoriesOwnerRepoCommitsRoute
  '/_auth/repositories/$owner/$repo/pulls/new': typeof AuthRepositoriesOwnerRepoPullsNewRoute
  '/_auth/repositories/$owner/$repo/pulls/': typeof AuthRepositoriesOwnerRepoPullsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/graph'
    | '/api/auth/$'
    | '/organizations'
    | '/repositories'
    | '/repositories/$owner/$repo'
    | '/organizations/$orgSlug'
    | '/repositories/$owner/$repo/branches'
    | '/repositories/$owner/$repo/commits'
    | '/repositories/$owner/$repo/pulls/new'
    | '/repositories/$owner/$repo/pulls'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/graph'
    | '/api/auth/$'
    | '/organizations'
    | '/repositories'
    | '/repositories/$owner/$repo'
    | '/organizations/$orgSlug'
    | '/repositories/$owner/$repo/branches'
    | '/repositories/$owner/$repo/commits'
    | '/repositories/$owner/$repo/pulls/new'
    | '/repositories/$owner/$repo/pulls'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/graph'
    | '/api/auth/$'
    | '/_auth/organizations/'
    | '/_auth/repositories/'
    | '/_auth/repositories/$owner/$repo'
    | '/_auth/organizations/$orgSlug/'
    | '/_auth/repositories/$owner/$repo/branches'
    | '/_auth/repositories/$owner/$repo/commits'
    | '/_auth/repositories/$owner/$repo/pulls/new'
    | '/_auth/repositories/$owner/$repo/pulls/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/graph': {
      id: '/_auth/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof AuthGraphRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/repositories/': {
      id: '/_auth/repositories/'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof AuthRepositoriesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/organizations/': {
      id: '/_auth/organizations/'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthOrganizationsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/organizations/$orgSlug/': {
      id: '/_auth/organizations/$orgSlug/'
      path: '/organizations/$orgSlug'
      fullPath: '/organizations/$orgSlug'
      preLoaderRoute: typeof AuthOrganizationsOrgSlugIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/repositories/$owner/$repo': {
      id: '/_auth/repositories/$owner/$repo'
      path: '/repositories/$owner/$repo'
      fullPath: '/repositories/$owner/$repo'
      preLoaderRoute: typeof AuthRepositoriesOwnerRepoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/repositories/$owner/$repo/commits': {
      id: '/_auth/repositories/$owner/$repo/commits'
      path: '/commits'
      fullPath: '/repositories/$owner/$repo/commits'
      preLoaderRoute: typeof AuthRepositoriesOwnerRepoCommitsRouteImport
      parentRoute: typeof AuthRepositoriesOwnerRepoRoute
    }
    '/_auth/repositories/$owner/$repo/branches': {
      id: '/_auth/repositories/$owner/$repo/branches'
      path: '/branches'
      fullPath: '/repositories/$owner/$repo/branches'
      preLoaderRoute: typeof AuthRepositoriesOwnerRepoBranchesRouteImport
      parentRoute: typeof AuthRepositoriesOwnerRepoRoute
    }
    '/_auth/repositories/$owner/$repo/pulls/': {
      id: '/_auth/repositories/$owner/$repo/pulls/'
      path: '/pulls'
      fullPath: '/repositories/$owner/$repo/pulls'
      preLoaderRoute: typeof AuthRepositoriesOwnerRepoPullsIndexRouteImport
      parentRoute: typeof AuthRepositoriesOwnerRepoRoute
    }
    '/_auth/repositories/$owner/$repo/pulls/new': {
      id: '/_auth/repositories/$owner/$repo/pulls/new'
      path: '/pulls/new'
      fullPath: '/repositories/$owner/$repo/pulls/new'
      preLoaderRoute: typeof AuthRepositoriesOwnerRepoPullsNewRouteImport
      parentRoute: typeof AuthRepositoriesOwnerRepoRoute
    }
  }
}

interface AuthRepositoriesOwnerRepoRouteChildren {
  AuthRepositoriesOwnerRepoBranchesRoute: typeof AuthRepositoriesOwnerRepoBranchesRoute
  AuthRepositoriesOwnerRepoCommitsRoute: typeof AuthRepositoriesOwnerRepoCommitsRoute
  AuthRepositoriesOwnerRepoPullsNewRoute: typeof AuthRepositoriesOwnerRepoPullsNewRoute
  AuthRepositoriesOwnerRepoPullsIndexRoute: typeof AuthRepositoriesOwnerRepoPullsIndexRoute
}

const AuthRepositoriesOwnerRepoRouteChildren: AuthRepositoriesOwnerRepoRouteChildren =
  {
    AuthRepositoriesOwnerRepoBranchesRoute:
      AuthRepositoriesOwnerRepoBranchesRoute,
    AuthRepositoriesOwnerRepoCommitsRoute:
      AuthRepositoriesOwnerRepoCommitsRoute,
    AuthRepositoriesOwnerRepoPullsNewRoute:
      AuthRepositoriesOwnerRepoPullsNewRoute,
    AuthRepositoriesOwnerRepoPullsIndexRoute:
      AuthRepositoriesOwnerRepoPullsIndexRoute,
  }

const AuthRepositoriesOwnerRepoRouteWithChildren =
  AuthRepositoriesOwnerRepoRoute._addFileChildren(
    AuthRepositoriesOwnerRepoRouteChildren,
  )

interface AuthRouteChildren {
  AuthGraphRoute: typeof AuthGraphRoute
  AuthOrganizationsIndexRoute: typeof AuthOrganizationsIndexRoute
  AuthRepositoriesIndexRoute: typeof AuthRepositoriesIndexRoute
  AuthRepositoriesOwnerRepoRoute: typeof AuthRepositoriesOwnerRepoRouteWithChildren
  AuthOrganizationsOrgSlugIndexRoute: typeof AuthOrganizationsOrgSlugIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthGraphRoute: AuthGraphRoute,
  AuthOrganizationsIndexRoute: AuthOrganizationsIndexRoute,
  AuthRepositoriesIndexRoute: AuthRepositoriesIndexRoute,
  AuthRepositoriesOwnerRepoRoute: AuthRepositoriesOwnerRepoRouteWithChildren,
  AuthOrganizationsOrgSlugIndexRoute: AuthOrganizationsOrgSlugIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
