/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthzRouteImport } from './routes/api/healthz'
import { Route as AppGraphRouteImport } from './routes/_app/graph'
import { Route as AppRepositoriesIndexRouteImport } from './routes/_app/repositories/index'
import { Route as AppOrganizationsIndexRouteImport } from './routes/_app/organizations/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppOrganizationsOrgSlugIndexRouteImport } from './routes/_app/organizations/$orgSlug/index'
import { Route as AppRepositoriesOwnerRepoRouteImport } from './routes/_app/repositories/$owner.$repo'
import { Route as ApiOgRepoOwnerRepoRouteImport } from './routes/api/og/repo.$owner.$repo'
import { Route as AppRepositoriesOwnerRepoCommitsRouteImport } from './routes/_app/repositories/$owner.$repo/commits'
import { Route as AppRepositoriesOwnerRepoBranchesRouteImport } from './routes/_app/repositories/$owner.$repo/branches'
import { Route as AppRepositoriesOwnerRepoPullsIndexRouteImport } from './routes/_app/repositories/$owner.$repo/pulls/index'
import { Route as AppRepositoriesOwnerRepoPullsNewRouteImport } from './routes/_app/repositories/$owner.$repo/pulls/new'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthzRoute = ApiHealthzRouteImport.update({
  id: '/api/healthz',
  path: '/api/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGraphRoute = AppGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoriesIndexRoute = AppRepositoriesIndexRouteImport.update({
  id: '/repositories/',
  path: '/repositories/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsIndexRoute = AppOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrganizationsOrgSlugIndexRoute =
  AppOrganizationsOrgSlugIndexRouteImport.update({
    id: '/organizations/$orgSlug/',
    path: '/organizations/$orgSlug/',
    getParentRoute: () => AppRoute,
  } as any)
const AppRepositoriesOwnerRepoRoute =
  AppRepositoriesOwnerRepoRouteImport.update({
    id: '/repositories/$owner/$repo',
    path: '/repositories/$owner/$repo',
    getParentRoute: () => AppRoute,
  } as any)
const ApiOgRepoOwnerRepoRoute = ApiOgRepoOwnerRepoRouteImport.update({
  id: '/api/og/repo/$owner/$repo',
  path: '/api/og/repo/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRepositoriesOwnerRepoCommitsRoute =
  AppRepositoriesOwnerRepoCommitsRouteImport.update({
    id: '/commits',
    path: '/commits',
    getParentRoute: () => AppRepositoriesOwnerRepoRoute,
  } as any)
const AppRepositoriesOwnerRepoBranchesRoute =
  AppRepositoriesOwnerRepoBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AppRepositoriesOwnerRepoRoute,
  } as any)
const AppRepositoriesOwnerRepoPullsIndexRoute =
  AppRepositoriesOwnerRepoPullsIndexRouteImport.update({
    id: '/pulls/',
    path: '/pulls/',
    getParentRoute: () => AppRepositoriesOwnerRepoRoute,
  } as any)
const AppRepositoriesOwnerRepoPullsNewRoute =
  AppRepositoriesOwnerRepoPullsNewRouteImport.update({
    id: '/pulls/new',
    path: '/pulls/new',
    getParentRoute: () => AppRepositoriesOwnerRepoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/graph': typeof AppGraphRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organizations': typeof AppOrganizationsIndexRoute
  '/repositories': typeof AppRepositoriesIndexRoute
  '/repositories/$owner/$repo': typeof AppRepositoriesOwnerRepoRouteWithChildren
  '/organizations/$orgSlug': typeof AppOrganizationsOrgSlugIndexRoute
  '/repositories/$owner/$repo/branches': typeof AppRepositoriesOwnerRepoBranchesRoute
  '/repositories/$owner/$repo/commits': typeof AppRepositoriesOwnerRepoCommitsRoute
  '/api/og/repo/$owner/$repo': typeof ApiOgRepoOwnerRepoRoute
  '/repositories/$owner/$repo/pulls/new': typeof AppRepositoriesOwnerRepoPullsNewRoute
  '/repositories/$owner/$repo/pulls': typeof AppRepositoriesOwnerRepoPullsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/graph': typeof AppGraphRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organizations': typeof AppOrganizationsIndexRoute
  '/repositories': typeof AppRepositoriesIndexRoute
  '/repositories/$owner/$repo': typeof AppRepositoriesOwnerRepoRouteWithChildren
  '/organizations/$orgSlug': typeof AppOrganizationsOrgSlugIndexRoute
  '/repositories/$owner/$repo/branches': typeof AppRepositoriesOwnerRepoBranchesRoute
  '/repositories/$owner/$repo/commits': typeof AppRepositoriesOwnerRepoCommitsRoute
  '/api/og/repo/$owner/$repo': typeof ApiOgRepoOwnerRepoRoute
  '/repositories/$owner/$repo/pulls/new': typeof AppRepositoriesOwnerRepoPullsNewRoute
  '/repositories/$owner/$repo/pulls': typeof AppRepositoriesOwnerRepoPullsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/pricing': typeof PricingRoute
  '/_app/graph': typeof AppGraphRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/organizations/': typeof AppOrganizationsIndexRoute
  '/_app/repositories/': typeof AppRepositoriesIndexRoute
  '/_app/repositories/$owner/$repo': typeof AppRepositoriesOwnerRepoRouteWithChildren
  '/_app/organizations/$orgSlug/': typeof AppOrganizationsOrgSlugIndexRoute
  '/_app/repositories/$owner/$repo/branches': typeof AppRepositoriesOwnerRepoBranchesRoute
  '/_app/repositories/$owner/$repo/commits': typeof AppRepositoriesOwnerRepoCommitsRoute
  '/api/og/repo/$owner/$repo': typeof ApiOgRepoOwnerRepoRoute
  '/_app/repositories/$owner/$repo/pulls/new': typeof AppRepositoriesOwnerRepoPullsNewRoute
  '/_app/repositories/$owner/$repo/pulls/': typeof AppRepositoriesOwnerRepoPullsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/graph'
    | '/api/healthz'
    | '/api/auth/$'
    | '/organizations'
    | '/repositories'
    | '/repositories/$owner/$repo'
    | '/organizations/$orgSlug'
    | '/repositories/$owner/$repo/branches'
    | '/repositories/$owner/$repo/commits'
    | '/api/og/repo/$owner/$repo'
    | '/repositories/$owner/$repo/pulls/new'
    | '/repositories/$owner/$repo/pulls'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/graph'
    | '/api/healthz'
    | '/api/auth/$'
    | '/organizations'
    | '/repositories'
    | '/repositories/$owner/$repo'
    | '/organizations/$orgSlug'
    | '/repositories/$owner/$repo/branches'
    | '/repositories/$owner/$repo/commits'
    | '/api/og/repo/$owner/$repo'
    | '/repositories/$owner/$repo/pulls/new'
    | '/repositories/$owner/$repo/pulls'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/pricing'
    | '/_app/graph'
    | '/api/healthz'
    | '/api/auth/$'
    | '/_app/organizations/'
    | '/_app/repositories/'
    | '/_app/repositories/$owner/$repo'
    | '/_app/organizations/$orgSlug/'
    | '/_app/repositories/$owner/$repo/branches'
    | '/_app/repositories/$owner/$repo/commits'
    | '/api/og/repo/$owner/$repo'
    | '/_app/repositories/$owner/$repo/pulls/new'
    | '/_app/repositories/$owner/$repo/pulls/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PricingRoute: typeof PricingRoute
  ApiHealthzRoute: typeof ApiHealthzRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOgRepoOwnerRepoRoute: typeof ApiOgRepoOwnerRepoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healthz': {
      id: '/api/healthz'
      path: '/api/healthz'
      fullPath: '/api/healthz'
      preLoaderRoute: typeof ApiHealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/graph': {
      id: '/_app/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof AppGraphRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repositories/': {
      id: '/_app/repositories/'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof AppRepositoriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations/': {
      id: '/_app/organizations/'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AppOrganizationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/organizations/$orgSlug/': {
      id: '/_app/organizations/$orgSlug/'
      path: '/organizations/$orgSlug'
      fullPath: '/organizations/$orgSlug'
      preLoaderRoute: typeof AppOrganizationsOrgSlugIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repositories/$owner/$repo': {
      id: '/_app/repositories/$owner/$repo'
      path: '/repositories/$owner/$repo'
      fullPath: '/repositories/$owner/$repo'
      preLoaderRoute: typeof AppRepositoriesOwnerRepoRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/og/repo/$owner/$repo': {
      id: '/api/og/repo/$owner/$repo'
      path: '/api/og/repo/$owner/$repo'
      fullPath: '/api/og/repo/$owner/$repo'
      preLoaderRoute: typeof ApiOgRepoOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/repositories/$owner/$repo/commits': {
      id: '/_app/repositories/$owner/$repo/commits'
      path: '/commits'
      fullPath: '/repositories/$owner/$repo/commits'
      preLoaderRoute: typeof AppRepositoriesOwnerRepoCommitsRouteImport
      parentRoute: typeof AppRepositoriesOwnerRepoRoute
    }
    '/_app/repositories/$owner/$repo/branches': {
      id: '/_app/repositories/$owner/$repo/branches'
      path: '/branches'
      fullPath: '/repositories/$owner/$repo/branches'
      preLoaderRoute: typeof AppRepositoriesOwnerRepoBranchesRouteImport
      parentRoute: typeof AppRepositoriesOwnerRepoRoute
    }
    '/_app/repositories/$owner/$repo/pulls/': {
      id: '/_app/repositories/$owner/$repo/pulls/'
      path: '/pulls'
      fullPath: '/repositories/$owner/$repo/pulls'
      preLoaderRoute: typeof AppRepositoriesOwnerRepoPullsIndexRouteImport
      parentRoute: typeof AppRepositoriesOwnerRepoRoute
    }
    '/_app/repositories/$owner/$repo/pulls/new': {
      id: '/_app/repositories/$owner/$repo/pulls/new'
      path: '/pulls/new'
      fullPath: '/repositories/$owner/$repo/pulls/new'
      preLoaderRoute: typeof AppRepositoriesOwnerRepoPullsNewRouteImport
      parentRoute: typeof AppRepositoriesOwnerRepoRoute
    }
  }
}

interface AppRepositoriesOwnerRepoRouteChildren {
  AppRepositoriesOwnerRepoBranchesRoute: typeof AppRepositoriesOwnerRepoBranchesRoute
  AppRepositoriesOwnerRepoCommitsRoute: typeof AppRepositoriesOwnerRepoCommitsRoute
  AppRepositoriesOwnerRepoPullsNewRoute: typeof AppRepositoriesOwnerRepoPullsNewRoute
  AppRepositoriesOwnerRepoPullsIndexRoute: typeof AppRepositoriesOwnerRepoPullsIndexRoute
}

const AppRepositoriesOwnerRepoRouteChildren: AppRepositoriesOwnerRepoRouteChildren =
  {
    AppRepositoriesOwnerRepoBranchesRoute:
      AppRepositoriesOwnerRepoBranchesRoute,
    AppRepositoriesOwnerRepoCommitsRoute: AppRepositoriesOwnerRepoCommitsRoute,
    AppRepositoriesOwnerRepoPullsNewRoute:
      AppRepositoriesOwnerRepoPullsNewRoute,
    AppRepositoriesOwnerRepoPullsIndexRoute:
      AppRepositoriesOwnerRepoPullsIndexRoute,
  }

const AppRepositoriesOwnerRepoRouteWithChildren =
  AppRepositoriesOwnerRepoRoute._addFileChildren(
    AppRepositoriesOwnerRepoRouteChildren,
  )

interface AppRouteChildren {
  AppGraphRoute: typeof AppGraphRoute
  AppOrganizationsIndexRoute: typeof AppOrganizationsIndexRoute
  AppRepositoriesIndexRoute: typeof AppRepositoriesIndexRoute
  AppRepositoriesOwnerRepoRoute: typeof AppRepositoriesOwnerRepoRouteWithChildren
  AppOrganizationsOrgSlugIndexRoute: typeof AppOrganizationsOrgSlugIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppGraphRoute: AppGraphRoute,
  AppOrganizationsIndexRoute: AppOrganizationsIndexRoute,
  AppRepositoriesIndexRoute: AppRepositoriesIndexRoute,
  AppRepositoriesOwnerRepoRoute: AppRepositoriesOwnerRepoRouteWithChildren,
  AppOrganizationsOrgSlugIndexRoute: AppOrganizationsOrgSlugIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PricingRoute: PricingRoute,
  ApiHealthzRoute: ApiHealthzRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOgRepoOwnerRepoRoute: ApiOgRepoOwnerRepoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
